In [2]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from io import StringIO

In [ ]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
editions_url = "https://www.olympedia.org/editions"
response = requests.get(editions_url, timeout=60)
soup = BeautifulSoup(response.content, "html.parser")

In [6]:
dfs = []
current_title = None
current_subtitle = None

for element in soup.find_all(["h2", "h3", "table"]):
    if element.name == "h2":
        current_title = element.get_text(strip=True)
    elif element.name == "h3":
        current_subtitle = element.get_text(strip=True)
    elif element.name == "table":
        df = pd.read_html(StringIO(str(element)))[0]
        df["title"] = current_title
        df["subtitle"] = current_subtitle
        dfs.append(df)

df = pd.concat(dfs)

df.rename(columns={"Unnamed: 7": "observation"}, inplace=True)

df.columns = df.columns.str.lower().str.replace(' ', '_')

In [7]:
df.head(20)

,#,year,city,country,opened,closed,competition,observation,title,subtitle
0,I,1896,Athina,NaN,6 April,15 April,6 – 13 April,NaN,Olympic Games,Summer
1,II,1900,Paris,NaN,NaN,NaN,14 May – 28 October,NaN,Olympic Games,Summer
2,III,1904,St. Louis,NaN,14 May,NaN,1 July – 26 November,NaN,Olympic Games,Summer
3,IV,1908,London,NaN,13 July,25 July,27 April – 31 October,NaN,Olympic Games,Summer
4,V,1912,Stockholm,NaN,6 July,15 July,5 May – 27 July,NaN,Olympic Games,Summer
5,VI,1916,Berlin,NaN,NaN,NaN,—,Not held due to war,Olympic Games,Summer
6,VII,1920,Antwerpen,NaN,14 August,30 August,23 April – 12 September,NaN,Olympic Games,Summer
7,VIII,1924,Paris,NaN,5 July,27 July,4 May – 27 July,NaN,Olympic Games,Summer
8,IX,1928,Amsterdam,NaN,28 July,12 August,17 May – 12 August,NaN,Olympic Games,Summer
9,X,1932,Los Angeles,NaN,30 July,14 August,30 July – 14 August,NaN,Olympic Games,Summer
10,XI,1936,Berlin,NaN,1 August,16 August,1 – 16 August,NaN,Olympic Games,Summer
11,XII,1940,Helsinki,NaN,NaN,NaN,—,Not held due to war,Olympic Games,Summer
12,XIII,1944,London,NaN,NaN,NaN,—,Not held due to war,Olympic Games,Summer
13,XIV,1948,London,NaN,29 July,14 August,26 July – 14 August,NaN,Olympic Games,Summer
14,XV,1952,Helsinki,NaN,19 July,3 August,14 July – 3 August,NaN,Olympic Games,Summer
15,XVI,1956,Melbourne,NaN,22 November,8 December,22 November – 8 December,NaN,Olympic Games,Summer
16,XVII,1960,Roma,NaN,25 August,11 September,25 August – 11 September,NaN,Olympic Games,Summer
17,XVIII,1964,Tokyo,NaN,10 October,24 October,11 – 24 October,NaN,Olympic Games,Summer
18,XIX,1968,Ciudad de México,NaN,12 October,27 October,12 – 27 October,NaN,Olympic Games,Summer
19,XX,1972,München,NaN,26 August,11 September,26 August – 11 September,NaN,Olympic Games,Summer